# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('Courses', 'Courses'), ('Useful Links', 'Useful Links'), ('Software', 'Software')], max_length=1500, null=True)),
                ('course_type', models.CharField(blank=True, max_length=1500, null=True)),
                ('software_type', models.CharField(blank=True, choices=[('LINEAR AND INTEGER PROGRAMMING', 'LINEAR AND INTEGER PROGRAMMING'), ('DECISION TREES', 'DECISION TREES'), ('RISK MANAGEMENT', 'RISK MANAGEMENT'), ('MULTICRITERIA ANALYSIS', 'MULTICRITERIA ANALYSIS'), ('VEHICLE ROUTING SOFTWARE', 'VEHICLE ROUTING SOFTWARE')], max_length=1500, null=True)),
                ('useful_link_type', models.CharField(blank=True, choices=[('Scopus', 'Scopus'), ('Journals of OR/MS', 'Journals of OR/MS'), ('Journals of POM', 'Journals of POM')], max_length=1500, null=True)),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=1500, null=True)),
                ('title_el', models.CharField(blank=True, max_length=1500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_el', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('order', models.IntegerField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['page__order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1500, null=True)),
                ('location', models.CharField(blank=True, max_length=1500, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('date', models.CharField(blank=True, max_length=1500, null=True)),
                ('internal', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1500)),
                ('name_en', models.CharField(blank=True, max_length=1500, null=True)),
                ('name_el', models.CharField(blank=True, max_length=1500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
                ('description_el', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=1500, null=True)),
                ('address_en', models.CharField(blank=True, max_length=1500, null=True)),
                ('address_el', models.CharField(blank=True, max_length=1500, null=True)),
                ('phone', models.CharField(blank=True, max_length=1500, null=True)),
                ('mobile', models.CharField(blank=True, max_length=1500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('fax', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lab Details',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1500)),
                ('lang_code', models.CharField(max_length=1500)),
                ('default', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=1500, null=True)),
                ('message', models.TextField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('name', models.CharField(blank=True, max_length=1500)),
                ('name_en', models.CharField(blank=True, max_length=1500, null=True)),
                ('name_el', models.CharField(blank=True, max_length=1500, null=True)),
                ('friendlyurl', models.SlugField(blank=True, null=True)),
                ('friendlyurl_en', models.SlugField(blank=True, null=True)),
                ('friendlyurl_el', models.SlugField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True)),
                ('menu', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1500)),
                ('name_en', models.CharField(blank=True, max_length=1500, null=True)),
                ('name_el', models.CharField(blank=True, max_length=1500, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('Head of Translog', 'Head of Translog'), ('Senior Research Fellows', 'Senior Research Fellows'), ('Research Fellows', 'Research Fellows'), ('Visiting Fellows', 'Visiting Fellows'), ('PhD Students', 'PhD Students')], max_length=1500)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_el', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cv_en', models.FileField(blank=True, max_length=1500, null=True, upload_to='cv/')),
                ('cv_gr', models.FileField(blank=True, max_length=1500, null=True, upload_to='cv/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=1500, null=True)),
                ('address_en', models.CharField(blank=True, max_length=1500, null=True)),
                ('address_el', models.CharField(blank=True, max_length=1500, null=True)),
                ('phone', models.CharField(blank=True, max_length=1500, null=True)),
                ('mobile', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('Conference Papers', 'Conference Papers'), ('Working Papers', 'Working Papers'), ('Journal Papers', 'Journal Papers'), ('Books', 'Books')], max_length=1500, null=True)),
                ('author', models.CharField(blank=True, max_length=1500, null=True)),
                ('location', models.CharField(blank=True, max_length=1500, null=True)),
                ('date', models.CharField(blank=True, max_length=1500, null=True)),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=1500, null=True)),
                ('title_el', models.CharField(blank=True, max_length=1500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_el', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('subject', models.CharField(blank=True, choices=[('Vehicle Routing Problems', 'Vehicle Routing Problems'), ('Scheduling Problems', 'Scheduling Problems'), ('Hazardous Material Logistical Problems', 'Hazardous Material Logistical Problems'), ('Green Vehicle Routing Problem', 'Green Vehicle Routing Problem'), ('Inventory Routing Problem', 'Inventory Routing Problem'), ('Green Inventory Routing Problem', 'Green Inventory Routing Problem')], default='Green Inventory Routing Problem', max_length=1500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Research Areas', 'Research Areas'), ('Projects', 'Projects')], max_length=1500)),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=1500, null=True)),
                ('title_el', models.CharField(blank=True, max_length=1500, null=True)),
                ('start_date', models.IntegerField(blank=True, null=True)),
                ('end_date', models.IntegerField(blank=True, null=True)),
                ('funded', models.CharField(blank=True, max_length=1500, null=True)),
                ('subject', models.CharField(blank=True, choices=[('Vehicle Routing Problems', 'Vehicle Routing Problems'), ('Scheduling Problems', 'Scheduling Problems'), ('Hazardous Material Logistical Problems', 'Hazardous Material Logistical Problems'), ('Green Vehicle Routing Problem', 'Green Vehicle Routing Problem'), ('Inventory Routing Problem', 'Inventory Routing Problem'), ('Green Inventory Routing Problem', 'Green Inventory Routing Problem')], default='Green Inventory Routing Problem', max_length=1500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_el', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Researches',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(blank=True, max_length=1500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=1500, null=True)),
                ('youtube', models.CharField(blank=True, max_length=1500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=1500, null=True)),
                ('scopus', models.CharField(blank=True, max_length=1500, null=True)),
                ('github', models.CharField(blank=True, max_length=1500, null=True)),
                ('other_link1', models.CharField(blank=True, max_length=1500, null=True)),
                ('other_link2', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Social'),
        ),
        migrations.AddField(
            model_name='labdetails',
            name='social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Social'),
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Page'),
        ),
    ]
