# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='page',
        ),
        migrations.RemoveField(
            model_name='event',
            name='internal',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
