# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 13:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170823_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, choices=[('Research', 'Research'), ('Publication', 'Publication'), ('Academic', 'Academic'), ('Research', 'Research')], default='Research Areas', max_length=1500, null=True)),
                ('sub_category', models.CharField(blank=True, choices=[('Research Areas', 'Research Areas'), ('Projects', 'Projects'), ('Conference Papers', 'Conference Papers'), ('Working Papers', 'Working Papers'), ('Journal Papers', 'Journal Papers'), ('Books', 'Books'), ('Courses', 'Courses'), ('Useful Links', 'Useful Links'), ('Software', 'Software')], default='Research', max_length=1500, null=True)),
                ('sub_sub_category', models.CharField(blank=True, choices=[('Scopus', 'Scopus'), ('Journals of OR/MS', 'Journals of OR/MS'), ('Journals of POM', 'Journals of POM'), ('LINEAR AND INTEGER PROGRAMMING', 'LINEAR AND INTEGER PROGRAMMING'), ('DECISION TREES', 'DECISION TREES'), ('RISK MANAGEMENT', 'RISK MANAGEMENT'), ('MULTICRITERIA ANALYSIS', 'MULTICRITERIA ANALYSIS'), ('VEHICLE ROUTING SOFTWARE', 'VEHICLE ROUTING SOFTWARE')], default='Research', max_length=1500, null=True)),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('start_date', models.IntegerField(blank=True, null=True)),
                ('end_date', models.IntegerField(blank=True, null=True)),
                ('funded', models.CharField(blank=True, max_length=1500, null=True)),
                ('subject', models.CharField(blank=True, choices=[('Vehicle Routing Problems', 'Vehicle Routing Problems'), ('Scheduling Problems', 'Scheduling Problems'), ('Hazardous Material Logistical Problems', 'Hazardous Material Logistical Problems'), ('Green Vehicle Routing Problem', 'Green Vehicle Routing Problem'), ('Inventory Routing Problem', 'Inventory Routing Problem'), ('Green Inventory Routing Problem', 'Green Inventory Routing Problem')], default='Green Inventory Routing Problem', max_length=1500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.CharField(blank=True, max_length=1500, null=True)),
                ('location', models.CharField(blank=True, max_length=1500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
    ]
