# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='friendlyurl_el',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='friendlyurl_en',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_el',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_en',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
