# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170823_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menu',
        ),
    ]
