# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_page_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='name_el',
            new_name='title_el',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='name',
        ),
    ]
