# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170823_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Publication', 'Publication'), ('Academic', 'Academic'), ('New', 'New'), ('Event', 'Event')], default='Research Areas', max_length=1500, null=True),
        ),
    ]
