# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170823_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='short_title',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Publications', 'Publications'), ('Academic', 'Academic'), ('New', 'New'), ('Event', 'Event')], default='Research Areas', max_length=1500, null=True),
        ),
    ]
