# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170824_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='long_title',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='long_title_el',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='long_title_en',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
