# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170824_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Areas', 'Areas'), ('Projects', 'Projects'), ('Conference Papers', 'Conference Papers'), ('Working Papers', 'Working Papers'), ('Journal Papers', 'Journal Papers'), ('Books', 'Books'), ('Courses', 'Courses'), ('Useful Links', 'Useful Links'), ('Software', 'Software')], default='Research', max_length=1500, null=True),
        ),
    ]
