# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170825_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='faculty_el',
        ),
        migrations.RemoveField(
            model_name='person',
            name='faculty_en',
        ),
    ]
