# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170825_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='faculty',
        ),
        migrations.AddField(
            model_name='person',
            name='faculty_el',
            field=models.CharField(blank=True, choices=[('Υπεύθυνος Εργαστηρίου', 'Υπεύθυνος Εργαστηρίου'), ('Πρεσβύτεροι Ερευνητές', 'Πρεσβύτεροι Ερευνητές'), ('Ερευνητές', 'Ερευνητές'), ('Επισκέπτες Ερευνητές', 'Επισκέπτες Ερευνητές'), ('Μεταπτυχιακοί Φοιτητές', 'Μεταπτυχιακοί Φοιτητές')], max_length=1500),
        ),
        migrations.AddField(
            model_name='person',
            name='faculty_en',
            field=models.CharField(blank=True, choices=[('Head of Translog', 'Head of Translog'), ('Senior Research Fellows', 'Senior Research Fellows'), ('Research Fellows', 'Research Fellows'), ('Visiting Research Fellows', 'Visiting Research Fellows'), ('PhD Students', 'PhD Students')], max_length=1500),
        ),
    ]
