# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20170825_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description_el',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
