# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170825_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author_el',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='author_en',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
