# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170825_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
