# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_person_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title_el',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='sub_sub_category',
            field=models.CharField(blank=True, choices=[('Scopus', 'Scopus'), ('Journals of OR/MS', 'Journals of OR/MS'), ('Journals of POM', 'Journals of POM'), ('Linear and integer Programming', 'LINEAR AND INTEGER PROGRAMMING'), ('Decision Trees', 'Decision Trees'), ('Risk Management', 'Risk Management'), ('Multicriteria Analysis', 'Multicriteria Analysis'), ('Vehicle Routing', 'Vehicle Routing')], default='Research', max_length=1500, null=True),
        ),
    ]
