# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20170826_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='journal',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='number',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='volume',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='year',
            field=models.IntegerField(blank=True, default=1995, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='sub_sub_category',
            field=models.CharField(blank=True, choices=[('Scopus', 'Scopus'), ('Journals of OR/MS', 'Journals of OR/MS'), ('Journals of POM', 'Journals of POM'), ('Linear and integer Programming', 'Linear and integer Programming'), ('Decision Trees', 'Decision Trees'), ('Risk Management', 'Risk Management'), ('Multicriteria Analysis', 'Multicriteria Analysis'), ('Vehicle Routing', 'Vehicle Routing')], default='Research', max_length=1500, null=True),
        ),
    ]
