# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20170920_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='level',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='year',
            field=models.IntegerField(blank=True, default=1994, null=True),
        ),
    ]
