# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20170920_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='conference',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='publisher',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='level',
            field=models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('Undergraduate ', 'Undergraduate')], default='Graduate', max_length=1500, null=True),
        ),
    ]
