# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20170924_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='research_gate',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
