# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_social_research_gate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Award',
            new_name='Home',
        ),
        migrations.AlterField(
            model_name='content',
            name='level',
            field=models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('Undergraduate', 'Undergraduate')], default='Graduate', max_length=1500, null=True),
        ),
    ]
