# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20171010_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
