# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20171010_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Areas', 'Areas'), ('Projects', 'Projects'), ('Conference Papers', 'Conference Papers'), ('Working Papers', 'Working Papers'), ('Journal Papers', 'Journal Papers'), ('Books', 'Books'), ('Courses', 'Courses'), ('Useful Links', 'Useful Links'), ('Software', 'Software')], default='Research', max_length=1500, null=True),
        ),
    ]
