# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20171011_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='image',
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
