# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20171011_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='github',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='other_link1',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='other_link2',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='research_gate',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='scopus',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
