# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20171011_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='conference',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Publications', 'Publications'), ('Academic', 'Academic'), ('News', 'News')], default='Research Areas', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='funded',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='level',
            field=models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('Undergraduate', 'Undergraduate')], default='Graduate', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='publisher',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Areas', 'Areas'), ('Projects', 'Projects'), ('Conference Papers', 'Conference Papers'), ('Working Papers', 'Working Papers'), ('Journal Papers', 'Journal Papers'), ('Books', 'Books'), ('Courses', 'Courses'), ('Useful Links', 'Useful Links'), ('Software', 'Software')], default='Research', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='sub_sub_category',
            field=models.CharField(blank=True, choices=[('Scopus', 'Scopus'), ('Journals of OR/MS', 'Journals of OR/MS'), ('Journals of POM', 'Journals of POM'), ('Linear and integer Programming', 'Linear and integer Programming'), ('Decision Trees', 'Decision Trees'), ('Risk Management', 'Risk Management'), ('Multicriteria Analysis', 'Multicriteria Analysis'), ('Vehicle Routing', 'Vehicle Routing')], default='Research', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.CharField(blank=True, choices=[('Vehicle Routing Problems', 'Vehicle Routing Problems'), ('Scheduling Problems', 'Scheduling Problems'), ('Hazardous Material Logistical Problems', 'Hazardous Material Logistical Problems'), ('Green Vehicle Routing Problem', 'Green Vehicle Routing Problem'), ('Inventory Routing Problem', 'Inventory Routing Problem'), ('Green Inventory Routing Problem', 'Green Inventory Routing Problem')], default='Green Inventory Routing Problem', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_el',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='volume',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='long_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='long_title_el',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='long_title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='short_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='short_title_el',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='short_title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_el',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_el',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='description_el',
            field=ckeditor.fields.RichTextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='faculty_el',
            field=models.CharField(blank=True, choices=[('Υπεύθυνος Εργαστηρίου', 'Υπεύθυνος Εργαστηρίου'), ('Πρεσβύτεροι Ερευνητές', 'Πρεσβύτεροι Ερευνητές'), ('Ερευνητές', 'Ερευνητές'), ('Επισκέπτες Ερευνητές', 'Επισκέπτες Ερευνητές'), ('Μεταπτυχιακοί Φοιτητές', 'Μεταπτυχιακοί Φοιτητές')], max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='faculty_en',
            field=models.CharField(blank=True, choices=[('Head of Translog', 'Head of Translog'), ('Senior Research Fellows', 'Senior Research Fellows'), ('Research Fellows', 'Research Fellows'), ('Visiting Research Fellows', 'Visiting Research Fellows'), ('PhD Students', 'PhD Students')], max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_el',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
